### ISSUE TITLE
binding-routing-key is showing as 'invalid-property' in application.yaml

### ISSUE THREAD

**Issue by HimanshubhusanRath** [spring-cloud/spring-cloud-stream-binder-rabbit#194]
Hi Team,

I am using the following configuration in **application.yaml** for a consumer client.

```
spring:
  cloud:
    stream:
      bindings:
        input: 
          destination: school.exchange
          binder: local_rabbit
          group: team.teachers
      binders: 
        local_rabbit:
          type: rabbit
          environment: 
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: /
      rabbit:
        bindings: 
          input: 
            consumer:
              binding-routing-key: school.teachers
```

But, Spring Tool Source is complaining about 'binding-routing-key' property and says it is invalid. 

Versions which I use is as follows:
**Spring Cloud: Finchley.SR1
Spring Cloud Stream: 2.0.1.RELEASE**

Can someone please tell me if this attribute is no longer supported in this versions or I am missing something here?
