### ISSUE TITLE
Unable to connect to existing RabbitMQ queue (creates a queue with destination.group naming scheme)

### ISSUE THREAD

**Issue by priyank-sriv** [spring-cloud/spring-cloud-stream-binder-rabbit#244]
#### High-level issue definition:
Incorrect queue binding while connecting with existing RabbitMQ infrastructure.

---

#### Details:

I have a scenario where I would like to use existing infrastructure (queues, exchanges and bindings), from a spring cloud stream application with rabbitmq binding.

Spring Cloud dependency:

```
Release version: Greenwich.RELEASE
Artifact: spring-cloud-starter-stream-rabbit
```

RabbitMQ infrastructure:

```
exchange: appExchange (direct)
queue: appQueue (durable)
binding: appExchange -> appQueue (routingKey: #)
```

Application Configuration:
```
spring:
  cloud:
    stream:
      bindings:
        appSink:
          destination: appExchange
          group: appQueue
          consumer:
            concurrency: 2
            bind-queue: false
            declare-exchange: false
            queue-name-group-only: true
```

This creates a new queue with the `destination.group` naming scheme resulting in `appExchange.appQueue` instead of connecting to the existing `appQueue`.

Alternatives that I've tried:

1. Destination and group with the same name:
```
        appSink:
          destination: appQueue
          group: appQueue
```
This creates a queue `appQueue.appQueue`

2. Blank destination

```
        appSink:
          group: appQueue
```
This creates a queue `appSink.appQueue`

Seems to me that `queue-name-group-only: true` is not being applied as I expect it. What am I missing or mis-configuring? Or is this a known limitation.

PS: I have been referring these source:
1. https://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/#_rabbitmq_consumer_properties
2. https://stackoverflow.com/a/50351798/6886283
