### ISSUE TITLE
Fanout is not working when having multiple replicas 

### ISSUE THREAD

**Issue by hassanbakerrts** [spring-cloud/spring-cloud-stream-binder-rabbit#249]
I have five replicas of a certain microservice on the cloud. I designed the exchange to be fanout and I noticed that these five consumers are attached to the same queue and when sending message to that queue only one of them will consume the message. I also  added the mirroring policy on the exchange from the rabbitmq UI and it still produces the same issue. Here is my configuration

Sender: 

```
            rabbit:
                bindings:
                    ExchangeName:
                        producer:
                            exchangeType: fanout
                            auto-bind-dlq: true


    cloud:
        refresh:
            # https://github.com/spring-cloud/spring-cloud-commons/issues/355
            refreshable: none
        stream:
            bindings:
                ExchangeName:
                    content-type: application/json
                    destination: x.exchange
```

Consumer: 

```
 stream:
            rabbit:
                bindings:
                    ExchangeName:
                        consumer:
                            auto-bind-dlq: true
                            exchangeType: fanout

            bindings:
                ExchangeName:
                    content-type: application/json
                    destination: x.exchange
                    group: x.queue
                    consumer:
                        max-concurrency: 5
                        max-attempts: 3
                        exchangeType: fanout
```
