### ISSUE TITLE
Rabbit binder health indicator should be disabled when management.health.rabbit.enabled=false

### ISSUE THREAD

**Issue by arnaud-deprez** [spring-cloud/spring-cloud-stream-binder-rabbit#256]
Hi, 

It is a complement to #55.
The configuration does not take into account the spring-boot property `management.health.rabbit.enabled`.

Moreover, I'm wondering what's the point to configure a RabbitMQ health indicator as `spring-boot` does it already.
IMO, I would remove [this](https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/blob/master/spring-cloud-stream-binder-rabbit/src/main/java/org/springframework/cloud/stream/binder/rabbit/config/RabbitServiceAutoConfiguration.java#L201-L214) completely.

**Comment by garyrussell** [comment]
Hmmm - I just merged this, but I think there's a problem when multiple rabbit binders are configured (to different brokers).

In that case, don't we need custom health indicators for each binder (since the boot configuration is not used at all).

So, I've reverted it for now.

**Comment by garyrussell** [comment]
Maybe we should just make it conditional on `management.health.rabbit.enabled` instead?

**Comment by arnaud-deprez** [comment]
@garyrussell making it conditional on `management.health.rabbit.enabled` was actually my first option.

But regarding the many binders thing, I'm not sure to get you. 
From what I understand, the current implementation just creates one `RabbitHealthIndicator` however many binders you have, doesn't ?
Also if the boot configuration is not used, how this one will be used ? 
It looks to me that it expects few things coming from spring-boot (or unless someone is doing all this configuration manually).

**Comment by garyrussell** [comment]
@arnaud-deprez See [Connecting to Multiple Systems[(https://cloud.spring.io/spring-cloud-static/spring-cloud-stream/2.2.0.RELEASE/spring-cloud-stream.html#multiple-systems).

Consider the following:

```yaml
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  cloud:
    stream:
      binders:
        rabbit1:
          type: rabbit
          default-candidate: true
          environment:
            spring:
              rabbitmq:
                addresses: 10.0.0.3
        rabbit2:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                addresses: 10.0.0.13
      bindings:
        input:
          binder: rabbit1
        input2:
          binder: rabbit2
```

We get 3 health indicators - one for the boot config and one for each of the binders, which do not use the boot config.

One indicator is not enough since it uses a `RabbitTemplate` configured to connect to a specific broker address.
