### ISSUE TITLE
Upgrade Spring Cloud Horsham SR3 to Horsham SR5, configure the routingKeyExpression parameter, and an exception occurs when the project starts

### ISSUE THREAD

**Issue by tangdelong** [spring-cloud/spring-cloud-stream-binder-rabbit#294]
configuration:    
```
spring:
  application:
    name: spring-cloud-rabbit-service-1
  cloud:
    stream:
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 127.0.0.1
                port: 5672
                username: guest
                password: guest
                virtual-host: /
      bindings:
        myOutput:
          destination: my-messages
          binder: local_rabbit
      rabbit:
          bindings:
            myOutput:
              producer:
                exchangeType: direct 
                routingKeyExpression:  headers.key
                queueNameGroupOnly: true 

```

start exception  as follows:

```
Failed to bind properties under 'spring.cloud.stream.rabbit.bindings.myoutput.producer.routing-key-expression' to org.springframework.expression.Expression:

    Property: spring.cloud.stream.rabbit.bindings.myoutput.producer.routingkeyexpression
    Value: headers.key
    Origin: class path resource [application.yml]:64:37
    Reason: No converter found capable of converting from type [java.lang.String] to type [org.springframework.expression.Expression]
```
