### ISSUE TITLE
How to customize Rabbit ConnectionFactory

### ISSUE THREAD

**Issue by rburgst** [spring-cloud/spring-cloud-stream-binder-rabbit#295]
I would need to customize the rabbit `ConnectionFactory` that is being used (having multiple binders of type RMQ). 
I have tried to add my custom `ConnectionFactory` to the spring application context but this is ignored when creating the new nested spring application in `org.springframework.cloud.stream.binder.DefaultBinderFactory#getBinderInstance`.

I havent found a way to do this neither by inspecting the code nor in the documentation.

**Comment by garyrussell** [comment]
Please show code/config; what is the nature of the customization needed?

**Comment by rburgst** [comment]
we need to auto provision client certificates which are done by registering to a custom service. Only once registered we can connect to the RMQ instance using the newly created cert.
I will try and come up with a sample showing this.

**Comment by rburgst** [comment]
see https://github.com/rburgst/spring-cloud-stream-rabbit-custom-cf

**Comment by rburgst** [comment]
The sample is very basic but shows that the custom configured `com.rabbitmq.client.ConnectionFactory` is being ignored.

**Comment by garyrussell** [comment]
OK; I'll see if I can figure out a work around for you.

**Comment by garyrussell** [comment]
Does it have to be a custom RMQ factory? Or can you use `useSslProtocol(SSLContext context)` on the standard RMQ factory to handle the certs (I think there's a relatively easy work around for that).

**Comment by garyrussell** [comment]
The only work around I could come up with will only work with auto-provisioning disabled (which means we must provision, at least for anonymous consumers - those with no `group`):

```java
@SpringBootApplication(exclude = RabbitAutoConfiguration.class)
@EnableBinding({ Rabbit1Sink.class, Rabbit2Sink.class })
public class DemoApplication {

	private ConnectionFactory connectionFactory(String host, int port, String user, String pw) {
		com.rabbitmq.client.ConnectionFactory rcf = new CustomRCF();
		CachingConnectionFactory cacheConnFact = new CachingConnectionFactory(rcf) {};
		cacheConnFact.afterPropertiesSet();
		return cacheConnFact;
	}

	// For consumers
	@Bean
	ListenerContainerCustomizer<AbstractMessageListenerContainer> containerCustomizer() {
		return (container, destinationName, group) -> {
			if ("externalQueue".equals(group) || "anotherQueue".equals("group")) {
				container.setConnectionFactory(connectionFactory("localhost", 5672, "guest", "guest"));
				// could do exchange/queue/binding provisioning here too
			}
			else if (group == null) { // anon consumer
				container.setConnectionFactory(connectionFactory("localhost", 5672, "guest", "guest"));
				RabbitAdmin admin = new RabbitAdmin(container.getConnectionFactory());
				container.getConnectionFactory().addConnectionListener(connection -> {
					// Need to declare/bind anonymous queues here
					admin.declareQueue(new AnonymousQueue(() -> destinationName));
				});
			}
		};
	}

	// For producers
	@Bean
	ProducerMessageHandlerCustomizer<AmqpOutboundEndpoint> producerCustomizer() {
		return (handler, destinationName) -> {
			if ("rabbit2.exchange".equals(destinationName)) {
				handler.getRabbitTemplate()
						.setConnectionFactory(connectionFactory("localhost", 5672, "guest", "guest"));
			}
		};
	}

	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args);
	}

}


class CustomRCF extends com.rabbitmq.client.ConnectionFactory {


	private static final Logger log = LoggerFactory.getLogger(CustomRCF.class);

	@Override
	protected AMQConnection createConnection(ConnectionParams params, FrameHandler frameHandler, MetricsCollector metricsCollector) {
		log.info("creating connection");

		return super.createConnection(params, frameHandler, metricsCollector);
	}
}
```
You have to remove the `environment` from the binders so we get visibility to the customizers...

```yaml
spring:
  cloud:
    stream:
      rabbit:
        bindings:
          rabbit1SubscriptionChannel:
            consumer:
              declareExchange: false
              bindingRoutingKey: "client.*.notification.#"
              queueNameGroupOnly: true
              bindQueue: false
          rabbit2SubscriptionChannel:
            consumer:
              declareExchange: false
              queueNameGroupOnly: true
              bindQueue: false
      bindings:
        rabbit1SubscriptionChannel:
          binder: rabbit1
          contentType: text/plain;charset=UTF-8
          destination: amq.topic # exchange
          group: externalQueue # queue
        rabbit2SubscriptionChannel:
          binder: rabbit2
          destination: rabbit2.exchange
          contentType: application/json
#          group: anotherQueue
      binders:
        rabbit1:
          type: rabbit
        rabbit2:
          type: rabbit
      default-binder: rabbit2
```
