### ISSUE TITLE
routing-key-expression not working in combination with dynamic destination

### ISSUE THREAD

**Issue by hectoryo** [spring-cloud/spring-cloud-stream-binder-rabbit#309]
I've the need of combining the use of a dynamic destination and to specify the routing key used while writing in the specified exchange by the destination.

in the properties I've
```yaml
...
spring:
  cloud:
    stream:
      defaultBinder: rabbit
      bindings:
        mybinding-out-0:
#          destination: destinationExchange
          binder: rabbit
      rabbit:
        bindings:
          mybinding-out-0:
            producer:
              transacted: true
              routing-key-expression: headers.myRoutingKeyHeader
...
```

```java
public Message<?> process(Message<?> message) {
        //...
        Message<?> messageToSend = MessageBuilder.fromMessage(message)
                    .setHeader("myRoutingKeyHeader", "myRoutingKey")
                    .setHeader("spring.cloud.stream.sendto.destination", "destinationExchange")
                    .build();
        //...
        return messageToSend;
    }
```

this writes the message on the exchange `destinationExchange ` but with the routing key being `destinationExchange`

the expected behaviour is to have the routing key `myRoutingKey`

in fact, if I disable the dynamic destination 

```yaml
...
spring:
  cloud:
    stream:
      defaultBinder: rabbit
      bindings:
        mybinding-out-0:
          destination: destinationExchange
          binder: rabbit
      rabbit:
        bindings:
          mybinding-out-0:
            producer:
              transacted: true
              routing-key-expression: headers.myRoutingKeyHeader
...
```

```java
public Message<?> process(Message<?> message) {
        //...
        Message<?> messageToSend = MessageBuilder.fromMessage(message)
                    .setHeader("myRoutingKeyHeader", "myRoutingKey")
                    //.setHeader("spring.cloud.stream.sendto.destination", "destinationExchange")
                    .build();
        //...
        return messageToSend;
    }
```

then the routing key works fine but at the cost of loosing dynamic destination

**Comment by garyrussell** [comment]
That's because those producer properties are properties of the named destination (which is `mybinding-out-0` when no `destination` is provided.

To apply properties to dynamic destinations, they must be set as defaults:

```yaml
spring:
  cloud:
    stream:
      defaultBinder: rabbit
      bindings:
        mybinding-out-0:
#          destination: destinationExchange
          binder: rabbit
      rabbit:
        default:
          producer:
            routing-key-expression: headers.myRoutingKeyHeader
            transacted: true
```

In future, please ask questions if something does not work as expected on Stack Overflow; GitHub issues are for reporting bugs or asking for a new feature.

**Comment by hectoryo** [comment]
ok, it seems I was a bit confused with how the dynamic bindings work.
I can confirm that the suggested solution work and I even went further away and removed mybinding-out-0 as it looks to be useless for my use case.
THe final properties I used are as follows:
```yaml
spring:
  cloud:
    stream:
      defaultBinder: rabbit
      rabbit:
        default:
          producer:
            routing-key-expression: headers.myRoutingKeyHeader
            transacted: true
```
