### ISSUE TITLE
Messages silently discarded due to changed republishToDlq default

### ISSUE THREAD

**Issue by stefnoten** [spring-cloud/spring-cloud-stream-binder-rabbit#313]
In c2ed214, the default value of republishToDlq was changed to `true`. With our setup, this caused unsuccessfully consumed messages to be **silently discarded** instead of being sent to the DLQ:

* With `republishToDlq=false` (old behaviour): rabbitmq itself republishes to the DLQ
* With `republishToDlq=true` (new behaviour): spring republishes to the DLQ, but our configured rabbitmq user did not have permissions to send messages to the configured DLX

Additional context: all our Rabbitmq exchanges/queues/bindings/users/permissions are set up up-front, so we do not use any auto declaration or binding. See below for our exact config.

### Actionable issues

* when republishing to the DLQ fails, the **message should not be acked** since it causes the message to be lost. With us, the cause was permissions, but we assume this could also be caused by network issues.
* changes such as these are currently **not documented anywhere** (unless we missed this?). However we feel it's quite important to be able to consult some kind of changelog to at least know which areas are impacted by an upgrade (e.g. to retest).

### Our config

```
spring:
  cloud:
    stream:
      bindings:
        input:
          consumer:
            max-attempts: 3
          destination: # ...
          group: # ...
          binder: # ...
      rabbit:
        bindings:
          input:
            consumer:
              missing-queues-fatal: true
              queue-name-group-only: true
              declare-exchange: false
              bind-queue: false
              requeue-rejected: false
              transacted: true
```
