### ISSUE TITLE
using routing-key-expression with partitioning

### ISSUE THREAD

**Issue by declan782** [spring-cloud/spring-cloud-stream-binder-rabbit#330]
hello,
I'm trying the rabbit partitioning sample in spring-cloud-stream-samples with below configuration, to specify a fixed routing key for my messages:
```
spring:
  cloud:
    stream:
      bindings:
        generate-out-0:
          destination: partitioned.destination
          producer:
            partition-key-expression: headers['partitionKey'] - 1
            partition-count: 4
      rabbit:
        bindings:
          generate-out-0:
            producer:
              routing-key-expression: '''myRoutingKey''' 
```

however, in the generated message, the message's routing key becomes "myRoutingKey-null", I guess it's not expected? is it an issue or I miss something?  Thanks.
