### ISSUE TITLE
using publisher confirm function for Rabbit MQ The official example did not pass

### ISSUE THREAD

**Issue by LiuYawei2019** [spring-cloud/spring-cloud-stream-binder-rabbit#334]
Prepare to use Spring Cloud Stream to complete RabbitMQ integration in the upcoming application. The business is mainly related to finance, and try to keep the data as strong as possible. Therefore, a confirmation mode from the publisher is required.The instance through the official website does not achieve the effect of asynchronous validation. (https://docs.spring.io/spring-cloud-stream-binder-rabbit/docs/3.1.3/reference/html/spring-cloud-stream-binder-rabbit.html#publisher-confirms). This is a bit pessimistic, looking at the source code doesn't show that the StreamBrigde object is capable of asynchronous notification.
application.yml Configuration context:
```yaml
spring:
  rabbitmq:
    publisher-confirm-type: correlated
    publisher-returns: true
    addresses: IPs
    ssl:
      enabled: false
  cloud:
    stream:
      rabbit:
        binder:
          nodes: IPs
          admin-addresses: IPs
        bindings:
          sender-out-0:
            producer:
              useConfirmHeader: true
      source: sender
      bindings:
        sender-out-0:
          destination: rabbit-confirm #交换器名称
          group: rabbit-confirm-group #队列名称
          binder: rabbit #绑定器
          producer:
            errorChannelEnabled: true
        confirm-in-0:
          destination: rabbit-confirm #交换器名称
          group: rabbit-confirm-group #队列名称
          binder: rabbit #绑定器
    function:
      definition: confirm
````
The test method is as follows:
```java
@PostMapping("/publishConfirm")
    public void publishConfirm(@RequestBody String body) {
        CorrelationData correlationData = new CorrelationData(UUID.randomUUID().toString());
        correlationData.getFuture().addCallback(new ListenableFutureCallback<CorrelationData.Confirm>() {
            @Override
            public void onFailure(Throwable ex) {
                System.out.println(ex.getMessage());
            }

            @Override
            public void onSuccess(CorrelationData.Confirm result) {
                System.out.println(result.toString());
            }
        });

        Message<?> message = MessageBuilder.withPayload(body)
                .setHeader(AmqpHeaders.PUBLISH_CONFIRM_CORRELATION, correlationData).build();
        streamBridge.send("rabbit-confirm", message);

        try {
            correlationData.getFuture().get(10, TimeUnit.SECONDS);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```
Thank you for your answers and guidance. thank you!
