### ISSUE TITLE
Issue when the Rabbit MQ Exchange is aqm.default

### ISSUE THREAD

**Issue by LiuYawei2019** [spring-cloud/spring-cloud-stream-binder-rabbit#340]
Environmental information:
```
spring-boot 2.4.6
spring-cloud 2020.0.3
spring-cloud-stream 3.1.3
```
An existing queue `queue. tas_check` is bound to the default exchange(amq.default),Send messages to queue `queue. tas_check` via the StreamBridge of cloud-stream.The partial configuration is as follows(Use yml configuration)：
```
spring:
  cloud:
    stream:
      bindings:
        tasCheck-out-0:
          binder: rabbit
          destination: amq.default
          group: queue.tas_check
       rabbit:
         bindings:
           tasCheck-out-0:
             producer:
               exchangeType: direct
               declareExchange: false
               queueNameGroupOnly: true
```
The error log is as follows:
`ERROR|CachingConnectionFactory:748|Shutdown Signal: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no exchange 'amq.default' in vhost '/', class-id=60, method-id=40)`
The following questions are referred to:
https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/issues/189
The following configuration was tried:
```
spring:
  cloud:
    stream:
      bindings:
        tasCheck-out-0:
          binder: rabbit
          destination: amq.direct
          group: queue.tas_check
       rabbit:
         bindings:
           tasCheck-out-0:
             producer:
               exchangeType: direct
               declareExchange: false
               queueNameGroupOnly: true
```
You can receive messages by observing the Exchange using Rabbit Admin, Can receive ack as true. But it's not routed to the queue`queue. tas_check`.
The following configuration was tried:
```
spring:
  cloud:
    stream:
      bindings:
        tasCheck-out-0:
          binder: rabbit
          destination: amq.direct
          group: queue.tas_check
       rabbit:
         bindings:
           tasCheck-out-0:
             producer:
               exchangeType: direct
               declareExchange: false
               queueNameGroupOnly: true
               routingKeyExpression: '''queue.tas_check'''
```
The error message is:
```
Property: spring.cloud.stream.rabbit.bindings.tasCheck-out-0.producer.routing-key-expression
    Value: 'queue.tas_check'
    Origin: class path resource [application.yml] - 37:37
    Reason: No converter found capable of converting from type [java.lang.String] to type [org.springframework.expression.Expression]
```
The above question is very confusing, whether there is any difference in this version that causes this problem.

**Comment by LiuYawei2019** [comment]
A separate test found that `routingKeyExpression: '''queue.tas_check'''` parsed properly, but there was an overwrite between components that caused the Spel expression parser to be lost.

**Comment by LiuYawei2019** [comment]
If 3.1.3 is used, error `routingKeyExpression: '''queue.tas_check'''` cannot be resolved. Add the following code to solve the problem.
```
spring:
  cloud:
    stream:
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              main:
                sources: org.springframework.cloud.stream.config.SpelExpressionConverterConfiguration
```
