### ISSUE TITLE
Question: how is the RabbitConsumerProperties changed?

### ISSUE THREAD

**Issue by erikthorselius** [spring-cloud/spring-cloud-stream-binder-rabbit#39]
Hi, I'm new to spring but how do I change the RabbitConsumerProperties from application.yml?

**Comment by ilayaperumalg** [comment]
Hi, 

The doc for this is available [here] (http://docs.spring.io/spring-cloud-stream/docs/Brooklyn.BUILD-SNAPSHOT/reference/htmlsingle/index.html#_rabbitmq_consumer_properties).

You can set the properties in your app's application.yml like this:

```
spring:
  cloud:
    stream:
      rabbit:
         bindings:
            <channelName>:
               consumer:
                   prefetch: 10
```
