### ISSUE TITLE
How to set the routingKey when sending a message in a spring-cloud stream channel?

### ISSUE THREAD

**Issue by SimonALau** [spring-cloud/spring-cloud-stream-binder-rabbit#57]
Here is the thing, I am using the` spring-cloud-stream` to handle the AMQP messages with the `spring-cloud-stream-binder-rabbit` binder. 

Every thing just works greatly in the `demoInput` which is the message consumer channel. I can receive all those messages whose `routingKey` are matched.

But the problems coming up on the producer channel `demoOutput`, all messages sent through this channel are with the default `routingKey`, which is same with the exchange name. No matter what i did (e.g., giving the `bingdingRoutingKey` in the rabbit producer configuration, or setting the `rabbitmq.ROUTING_KEY` header) it just doesn't work.

So, how to set the `routingKey` when sending the message? Doesn't it supported yet?

This is my application, it supposed to send a message from `demoOutput` and then message can be received in `demoInput` channel, but i never received message in the `demoInput`. Here is the configurations, 
```
spring:
  cloud:
    stream:
      bindings:
        demoInput:
          destination: exchange.a
          binder: rabbit1
          group: group1
        demoOutput:
          destination: exchange.a
          binder: rabbit1
          producer:
            requiredGroups: group1
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: _xxx.xxx.xxx.xxx_
                port: 5672
                username: _xxx_
                password: _xxx_
                virtual-host: /
      rabbit:
        bindings:
          demoInput:
            consumer:
              bindingRoutingKey: test.#
          demoOutput:
            producer:
              bindingRoutingKey: test.a
```

Here is the producer,
```
@Service
public class MessageProducer {
    @Autowired
    private MessageChannel demoOutput;

    public void produce (String msg) {
        demoOutput.send(MessageBuilder.withPayload(msg).build());
    }
}
```
And here is the consumer,
```
@Component
public class MessageConsumer {
    @StreamListener("demoInput")
    public void consume (String msg) {
        System.err.println(msg);
    }
}
```
